env:
  es2021: true
  node: true
  serviceworker: true
  browser: true
root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:vue/essential
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
  - plugin:css/recommended
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - prettier
  - vue
  - css
rules:
  semi: 0
  no-console: 2
  prettier/prettier:
    - error
